export const EMAIL_CONFIRM = "EMAIL_CONFIRM"
export const EMAIL_CONFIRM_SUCCESS = "EMAIL_CONFIRM_SUCCESS" 
export const EMAIL_CONFIRM_FAIL = "EMAIL_CONFIRM_FAIL" 

export const CONFIRM_PASSWORD = "CONFIRM_PASSWORD"
export const CONFIRM_PASSWORD_SUCCESS = "CONFIRM_PASSWORD_SUCCESS" 
export const CONFIRM_PASSWORD_FAIL = "CONFIRM_PASSWORD_FAIL" 
